export const images = {
  'card_001': require('../assets/dissector/card_001.jpg'),
  'card_002': require('../assets/dissector/card_002.jpg'),
  'card_003': require('../assets/dissector/card_003.jpg'),
  'card_004': require('../assets/dissector/card_004.jpg'),
  'card_005': require('../assets/dissector/card_005.jpg'),
  'card_006': require('../assets/dissector/card_006.jpg'),
  'card_007a': require('../assets/dissector/card_007a.jpg'),
  'card_007b': require('../assets/dissector/card_007b.jpg'),
  'card_007c': require('../assets/dissector/card_007c.jpg'),
  'card_008': require('../assets/dissector/card_008.jpg'),
  'card_010': require('../assets/dissector/card_010.jpg'),
  'card_011': require('../assets/dissector/card_011.jpg'),
  'card_012': require('../assets/dissector/card_012.jpg'),
  'card_013': require('../assets/dissector/card_013.jpg'),
  'card_014': require('../assets/dissector/card_014.jpg'),
  'card_015': require('../assets/dissector/card_015.jpg'),
  'card_016': require('../assets/dissector/card_016.jpg'),
  'card_017': require('../assets/dissector/card_017.jpg'),
  'card_018': require('../assets/dissector/card_018.jpg'),
  'card_019': require('../assets/dissector/card_019.jpg'),
  'card_020': require('../assets/dissector/card_020.jpg'),
  'card_021': require('../assets/dissector/card_021.jpg'),
  'card_022': require('../assets/dissector/card_022.jpg'),
  'card_023': require('../assets/dissector/card_023.jpg'),
  'card_024': require('../assets/dissector/card_024.jpg')
};

